#!/bin/sh

mkdir etc,dev,mnt,sys,tmp,proc,root
sudo cp -d /usr/arm-linux-gnueabi/lib/*.so* ./lib

cd dev/
sudo mknod -m 666 console c 5 1
sudo mknod -m 666 null c 1 3
sudo mknod -m 666 dev/tty1 c 4 1
sudo mknod -m 666 dev/tty2 c 4 2
sudo mknod -m 666 dev/tty3 c 4 3
sudo mknod -m 666 dev/tty4 c 4 4

mkdir -p etc/init.d
touch etc/init.d/rcS
chmod 777 etc/init.d/rcS
touch etc/fstab
touch etc/inittab

echo "#!/bin/sh" > etc/init.d/rcS
echo "PATH=/bin:/sbin:/usr/bin:/usr/sbin" >> etc/init.d/rcS
echo "export LD_LIBRARY_PATH=/lib:/usr/lib" >> etc/init.d/rcS
echo "/bin/mount -n -t ramfs ramfs /var" >> etc/init.d/rcS
echo "/bin/mount -n -t ramfs ramfs /tmp" >> etc/init.d/rcS
echo "/bin/mount -n -t sysfs none /sys" >> etc/init.d/rcS
echo "/bin/mount -n -t ramfs none /dev" >> etc/init.d/rcS
echo "/bin/mkdir /var/tmp" >> etc/init.d/rcS
echo "/bin/mkdir /var/modules" >> etc/init.d/rcS
echo "/bin/mkdir /var/run" >> etc/init.d/rcS
echo "/bin/mkdir /var/log" >> etc/init.d/rcS
echo "/bin/mkdir -p /dev/pts" >> etc/init.d/rcS
echo "/bin/mkdir -p /dev/shm" >> etc/init.d/rcS
echo "/sbin/mdev -s" >> etc/init.d/rcS
echo "/bin/mount -a" >> etc/init.d/rcS
echo "echo "-----------------------------------"" >> etc/init.d/rcS
echo "echo "*****welcome to vexpress board*****"" >> etc/init.d/rcS
echo "echo "-----------------------------------"" >> etc/init.d/rcS

echo "proc    /proc           proc    defaults        0       0" >> etc/fstab
echo "none    /dev/pts        devpts  mode=0622       0       0" >> etc/fstab
echo "mdev    /dev            ramfs   defaults        0       0" >> etc/fstab
echo "sysfs   /sys            sysfs   defaults        0       0" >> etc/fstab
echo "tmpfs   /dev/shm        tmpfs   defaults        0       0" >> etc/fstab
echo "tmpfs   /dev            tmpfs   defaults        0       0" >> etc/fstab
echo "tmpfs   /mnt            tmpfs   defaults        0       0" >> etc/fstab
echo "var     /dev            tmpfs   defaults        0       0" >> etc/fstab
echo "ramfs   /dev            ramfs   defaults        0       0" >> etc/fstab

echo "::sysinit:/etc/init.d/rcS" >> etc/fstab
echo "::askfirst:-/bin/sh" >> etc/fstab
echo "::restart:/sbin/init" >> etc/fstab
echo "::ctrlaltdel:/sbin/reboot" >> etc/fstab
echo "::shutdown:/bin/umount -a -r" >> etc/fstab



